# Generated by Django 5.0.6 on 2025-02-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('actor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('profile_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'actors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('director_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('profile_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'directors',
                'managed': False,
            },
        ),
    ]
