# Generated by Django 5.0.6 on 2025-02-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('banner_id', models.AutoField(primary_key=True, serialize=False)),
                ('url_banner', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'banners',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('episode_id', models.AutoField(primary_key=True, serialize=False)),
                ('episode_number', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('url_video', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'episodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movieactors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'movieactors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Moviedirectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'moviedirectors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Moviegenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'moviegenres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=155, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('poster_url', models.CharField(blank=True, max_length=255, null=True)),
                ('trailer_url', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('views', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movies',
                'managed': False,
            },
        ),
    ]
