# Generated by Django 5.0.6 on 2025-02-22 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviegenres',
            options={},
        ),
    ]
