# Generated by Django 5.0.6 on 2025-02-23 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_moviegenres_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviegenres',
            options={'managed': False},
        ),
    ]
