# Generated by Django 5.0.6 on 2025-05-08 10:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('report_type', models.CharField(choices=[('dashboard', 'Tổng quan'), ('movie', 'Thống kê phim'), ('episode', 'Thống kê tập phim'), ('actor', 'Thống kê diễn viên'), ('director', 'Thống kê đạo diễn'), ('comment', 'Thống kê bình luận')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
