# Generated by Django 5.0.6 on 2025-02-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monopolys',
            fields=[
                ('monopoly_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'monopolys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nations',
            fields=[
                ('nation_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'db_table': 'nations',
                'managed': False,
            },
        ),
    ]
