# Generated by Django 5.0.6 on 2025-01-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountEmailaddress',
        ),
        migrations.DeleteModel(
            name='AccountEmailconfirmation',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthtokenToken',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='id',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='DjangoSite',
        ),
        migrations.DeleteModel(
            name='SocialaccountSocialaccount',
        ),
        migrations.DeleteModel(
            name='SocialaccountSocialapp',
        ),
        migrations.DeleteModel(
            name='SocialaccountSocialappSites',
        ),
        migrations.DeleteModel(
            name='SocialaccountSocialtoken',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='ProfileUser',
        ),
    ]
