# Generated by Django 5.0.6 on 2025-01-20 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dateofbirth', models.DateField(blank=True, db_column='DateOfBirth', null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('idnumber', models.CharField(blank=True, db_column='idNumber', max_length=15, null=True)),
                ('url_img', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'profile_user',
                'managed': False,
            },
        ),
    ]
