# Generated by Django 5.0.6 on 2025-03-25 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_comments_reviews_watchlists'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
